spring:
  application:
    name: t1-java-demo
  datasource:
    jdbcUrl: jdbc:postgresql://localhost:5432/t1_demo
    username: postgres
    password: "25647"
    driverClassName: org.postgresql.Driver
  liquibase:
    enabled: true
    default-schema: t1_demo
    change-log: db/changelog/db.changelog-master.xml
    driver-class-name: org.postgresql.Driver
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/t1_demo
    user: postgres
    password: "25647"
security:
  token: tstrs4g434wyhser5htstrs4g434wyhser5htstrs4g434wyhser5htstrs4g434wyhser5htstrs4g434wyhser5h
  expiration: 86400000
tle_ms: 2000
logging:
  level:
    ROOT: ERROR
    ru.t1.java.demo.controller.ClientController: ERROR
    ru.t1.java.demo.aop.LoggingAspect: INFO
    org.apache.kafka: ERROR
    org.hibernate.SQL: ERROR

t1:
  scan-path: ru.t1.java.demo
  kafka:
    bootstrap:
      server: localhost:9092
    consumer:
      group-id: t1-demo
      max.poll.records: 10
    producer:
      enable: true
    topic:
      client_registration: t1_demo_client_registration
      client_id_registered: t1_demo_client_registered
      transaction_created: t1_demo_transactions
      account_created: t1_demo_accounts
      metric_race: t1_demo_metric_trace
    listener:
      poll-timeout: 1000


track:
  errors-to-track: JsonParseException, IOException
  kafka:
    enabled: ${TRACK_KAFKA_LOG_ENABLED:true}
    bootstrap-server: localhost:9092
    data-source-error-topic: t1_demo_data_source_error
    time-limit-exceed: t1_demo_time_limit_exceed
  db:
    enabled: false
  time-limit-exceed: 1000
